### ISSUE TITLE
Sanity checklist

### ISSUE THREAD

**Issue by Guria** [christianalfoni/addressbar#11]
### package.json
- [x] naming
- [x] correct urls
- [x] deps
- [x] authors
- [x] contributors
- [x] license: MIT
- [x] scripts
- [x] keywords
- [x] private: y/n
### README
- [x] badges at top, links at bottom
  - [x] npm
  - [x] build status
  - [ ] coverage
  - [x] standard
  - [x] commitizen
### tests
- [x] folder: `tests/`
- [x] could be ran on travis
- [x] testing API, not tied to implementation
### other files
- [x] LICENSE.md MIT
- [x] [CONTRIBUTING.md](CONTRIBUTING)
- [x] no generated content
- [x] .gitignore
- [ ] .npmignore
### workflow
- [ ] coverage
- [x] standard
- [x] protect `master`
- [x] commitizen + cz-customizable
- [x] ghooks + validate-commit-msg
- [x] semantic-release
  - [x] version 0.0.0
  - [x] travis
  - [ ] cracks
